<?php include 'includes/mainheader.php'; ?>

<body>
  <header>
    <div id="myCarousel" class="carousel slide" data-ride="carousel">
      <div class="carousel-inner" role="listbox" class="img-responsive">
        <div class="item active"><img src="images/mesalandsbanner.png" alt="Mesalands Banner"></div>  
      </div>
    </div>
    <div class="container-fluid">
      <a href="index.php"><img id="LogoImg" src="images/NMCollegeTransfer2.png" class="img-responsive" alt="Responsive Image"></a></div>
    </header>

    <!--Begin top nav-->
    <?php require 'includes/topnav.php'; ?>
    <!--End top nav-->

    <ol class="breadcrumb">
      <li>
        <a href="index.php">HOME</a>
      </li>
      <li>
        FAMILY QUICK FACTS
      </li>
    </ol>

    <div class="textbody"><h3>Family Life Quick Facts</h3>
      <p>Explanation</p>
      <table class="table table-bordered">
       <th class="col-md-1">4 YEAR SCHOOLS</th> <th class="col-md-1">Housing</th> <th class="col-md-1">Child Care</th> <th class="col-md-1">Parent Info</th>
       <tr><td>ENMU</td><td>As a student, you need a safe environment that gives you privacy, quiet time and a place to keep your stuff. You also need a place where you can feel comfortable hanging out with your friends, listen to music, or do whatever it is that you do to relax. You will find just the environment you need in our three residence halls and 300 apartments.<br /><a href="http://www.enmu.edu/services/housing/index.shtml">ENMU Housing</td><td>The Child Development Center-Welcome to the Child Development Center (CDC) Laboratory School! ENMU's Child Development Center has a proud history of serving as a laboratory school since 1949. <br /><a href="http://education.enmu.edu/projects/cdc.shtml">ENMU Child Care</a></td><td>Resource and information for current and future ENMU parents:<br /><a href="http://www.enmu.edu/index.php?option=com_content&view=article&id=853&Itemid=1507/parents/">Parent Info</a></td></tr>
       <tr><td>IAIA</td><td>There are two options for housing at IAIA—Center for Lifelong Education (CLE) Residence Center and our family housing apartments. Each area provides safe and secure housing in a healthy, positive, and inclusive environment.<br /><a href="https://iaia.edu/student-life/housing/">IAIA Housing</a></td><td>Child care is not available on campus.</td><td>The student life staff is ready to welcome your child to their new temporary home. We know you have questions, so we hope we can answer some of them on this page.<br /><a href="https://iaia.edu/student-life/for-parents/">Parent Info</a></td></tr>
       <tr><td>NAVAJO TECHNICAL<br />UNIVERSITY</td><td>NTU provides residential housing for both single students and students with families at the main campus.<br /><a href="http://www.navajotech.edu/campus-life/housing">Student Housing</td><td>The NTU Child Care Services Program operates within the Instructional Services Department.<br /><a href="http://www.navajotech.edu/campus-life/child-care">IAIA Child Care</a></td><td>No information found.</td></tr>
       <tr><td>NMHU</td><td>Students have a variety of choices when considering an on-campus residence. There are suitestyle residences and more traditional halls with both private and shared rooms; something for everyone.<br /><a href="http://www.nmhu.edu/highlands-university-housing/">NMHU Housing</a></td><td>Phone:<a href="tel:1-505-454-3250">505-454-3250</a><br /><a href="http://www.nmhu.edu/wp-content/uploads/2014/08/002420-catalog_unde-713201142520.pdf">NMHU Catalog</a></td><td><a href="http://www.nmhu.edu/alumnifoundation/nmhu-parents-club/">NMHU Parents Club</a></td></tr>
       <tr><td>NMT</td><td>We have many different Residence Hall and Apartment types, styles, cost, amenities and locations for you to choose from!<br /><a href="http://www.nmt.edu/welcome-to-res-life-residential-life">NMT Housing</a></td><td><a href="http://www.nmt.edu/childrens-center">NMT Children's Center</a></td><td><a href="http://www.nmt.edu/parent-information">Parent Info</a></td></tr>
       <tr><td>NMSU</td><td> Whether you are an undergraduate or a graduate student, single or married, with or without children, you are sure to find a place to call home at New Mexico State University.<br /><a href="http://housing.nmsu.edu/">NMSU Housing</a></td><td>Myrna’s Children’s Village offers early care and education programs for NMSU students, faculty, staff, and community families and children, six weeks to five years of age. <br /><a href="https://ci.nmsu.edu/programs/concentrations/eced/mcvi/">Myrna's Childrens Village</a></td><td>Family involvement plays an important role in the success of our students. NMSU’s caring community is committed to helping you to provide support and guidance for your student.<br /><a href="http://families.nmsu.edu/">Parents and Families</a></td></tr>
       <tr><td>NNMC</td><td>No housing available.</td><td>Child Care not available.</td><td>No information found.</td></tr>
       <tr><td>UNM</td><td>Residence Life and Student Housing offers many options to meet your housing needs.<br /><a href="http://housing.unm.edu/index.html">UNM Housing</a></td><td>The UNM Children’s Campus for Early Care and Education (UNMCC) is supported by student fees and is under the umbrella of Student Affairs and the College of Education. <br /><a href="https://childcare.unm.edu/index.html">Children's Campus for Early Care & Education</a></td><td>Staying connected gives parents the information they need to stay informed of university happenings and to aid their students to success. Come join the pack and help strengthen our Lobo Community!<br /><a href="http://parent.unm.edu/">UNM Parents & Families</a><br /><a href="http://parentassociation.unm.edu/index.html">UNM Parent Association</a></td></tr>
       <tr><td>WNMU</td><td>All students with less than 60 semester credit hours residing outside of the tri-county area (Grant, Luna, or Hidalgo counties in New Mexico) are required to live in University owned and operated residential facilities.<br /><a href="http://reslife.wnmu.edu/info/">WNMU Housing</a></td><td>The Early Childhood Programs at Western New Mexico University seek to support the highest quality of early care and education through community outreach, teacher education/training, and advocacy. <br /><a href="http://ecp.wnmu.edu/programs/cdc/cdc/">Child Development Center</a></td><td>No information found.</td></tr>
       <th>2 YEAR SCHOOLS</th><th>Housing</th><th>Child Care</th><th>Parent Info</th>
       <tr><td>CNM</td><td>CNM doesn't provide housing but they do have a list of resources:<br /><a href="https://www.cnm.edu/cnm-community/community-resources/housing">Housing</a></td><td>Tres Manos Child Development Center provides low cost, high quality child care to a limited number of CNM students.<br /><a href="https://www.cnm.edu/depts/financial-aid/resources/childcare.html">Tres Manos Child Development Center</a></td><td>As a parent of a current or incoming CNM student, you may have some questions about the college. Here is some information to help you out.<br /><a href="https://www.cnm.edu/cnm-community/parent-guide">Parent Guide to CNM</a></td></tr>
       <tr><td>CCC</td><td>CCC does not have on campus housing.<br /><a href="http://nnmc.edu/home/student-gateway/student-housing/">Student Housing</a></td><td>The Child Development Center opened in fall of 2007. It includes 2 lecture rooms, 2 observation rooms and the 3 classroom lab school.<br /><a href="http://www.cloviscenter.com/index.aspx?page=76">Clovis Community College Child Development Lab School</a><br />CCC's Kids College for the Summer of 2015 has something for every kid, ranging from health and fitness classes to hands-on science and art.<br /><a href="http://www.clovis.edu/kidscollege/index.aspx">Kids College</a></td><td>No information found.</td></tr>
       <tr><td>DIN&#201;</td><td>Diné College provides eight residential halls for students at the main campus in Tsaile and three residential halls for DC student athletes in Shiprock.<br /><a href="http://www.dinecollege.edu/residence/residencelife.php">Residence Life</a></td><td>The Tsaile Campus has two day-care facilities on campus that are run by the Navajo Nation’s Division of Social Services.<br /><a href="http://www.dinecollege.edu/services/student-services.php">Child Care</a></td><td>Dual Enrollment Parent Info:<br /><a href="http://www.dinecollege.edu/dual-credit-program/students-and-parents.php">Parent Info</a></td></tr>
       <tr><td>ENMU-ROSWELL</td><td>Sierra Vista Village at Eastern New Mexico University - ENMU - is a great space at the right price.<br /><a href="https://www.americancampus.com/student-apartments/nm/roswell/sierra-vista-village">Sierra Vista Village</a></td><td>The Child Development Center (CDC) is operated by Working Mother’s Day Nursery. <br /><a href="tel:1-575-624-7301">(575) 624-7301</a></td><td>We know you have a million things to worry about when your loved one is off at college, but their living environment shouldn't be one of them! <br /><a href="https://www.americancampus.com/student-apartments/nm/roswell/sierra-vista-village/contact-us">Housing Parent Info</a></td></tr>
       <tr><td>ENMU-RUIDOSO</td><td>No housing available.</td><td>No child care info found.</td><td><a href="http://ruidoso.enmu.edu/index.php/new-page/334-regsistration-faqs">FERPA Parent Info</a></td></tr>
       <tr><td>LUNA CC</td><td>It is the responsibility of students to obtain their own housing while attending the college.<br /><a href="https://www.luna.edu/student_support/">Student Support</a></td><td>The college offers its students the opportunity to enroll their children in the preschool while they attend school.<br /><a href="http://www.luna.edu/orientation/step5.html">Child Care</a></td><td>No information available.</td></tr>
       <tr><td>MESALANDS CC</td><td>Mesalands does not have campus housing.</td><td>No information available.</td><td><a href="http://www.mesalands.edu/about/consumer-information/ferpa/">Parent Info</a></td><tr>
        <tr><td>NMJC</td><td>We believe on-campus living provides both an enjoyable and rewarding experience in community living as well as the necessary support for academic success. On-campus housing for married couples or individuals with children is not provided.<br /><a href="http://www.nmjc.edu/studentservices/housing.aspx">NMJC Student Housing</a></td><td>No information available.</td><td><a href="http://www.nmjc.edu/parents/">Parent Info</a></td></tr>
        <tr><td>NMMI</td><td>Our Residence halls are designed to provide a safe environment for the cadets, an effective learning atmosphere and a comfortable home away from home.<br /><a href="https://www.nmmi.edu/admissions/Room_Board.htm">Room and Board</a></td><td>No child care available.</td><td>Information for NMMI Parents:<br /><a href="http://www.nmmi.edu/parents/">NMMI Parent & Families</a></td></tr>
        <tr><td>NMSU-ALAMOGORDO</td><td>NMSU Alamogordo does not have dormitories. However, there are various affordable apartment complexes and houses for rent, some located within walking distance.<br /><a href="http://nmsua.edu/admissions/prospective-students/housing/">Housing Resources</a></td><td>A list of child care providers can be obtained fro the NM Children, Youth, and Families, SSD at 2200 Indian Wells, 437-5950<br /><a href="http://nmsua.edu/current-students/helping-agencies/">Helping Agencies</a></td><td>As your student may have a desire to participate in Dual Credit it is important to know the rights that you as parents have and the rights that the students have under the FERPA policy.<br /><a href="http://nmsua.edu/admissions/dual-credit/information-for-parents/">Information for Parents</a></td></tr>
        <tr><td>NMSU-CARLSBAD</td><td>Although NMSU Carlsbad does not provide dormitory housing, the Student Services department is happy to help you find an affordable apartment.<br /><a href="https://carlsbad.nmsu.edu/students/all-students/student-life/">Student Life</a></td><td>No information found.</td><td><a href="https://carlsbad.nmsu.edu/students/all-students/student-handbook/family-education-rights-privacy-act-of-1974-ferpa/">Parent Info</a></td></tr>
        <tr><td>NMSU-DONA ANA</td><td>Housing is available to community college students on the same basis as it is for other New Mexico State University students.<br /><a href="http://housing.nmsu.edu/">NMSU Housing</a></td><td>No information found.</td><td>No information found.</td></tr>
        <tr><td>NMSU-GRANTS</td><td>No housing available.</td><td>Small Wonders Child Care Center, on the NMSU Grants campus, offers childcare to students, faculty, and staff for children, ages 6 weeks to 12 years, for an established fee.<br /><a href="https://grants.nmsu.edu/community/small-wonders/">Small Wonders Child Care</a></td><td>No information found.</td></tr>
        <tr><td>SAN JUAN COLLEGE</td><td>No housing available.</td><td>The primary purpose of the Child & Family Development Center (CFDC) on the campus of San Juan College (SJC) is to serve as a laboratory school for early childhood, nursing, psychology, dental and sociology students at the College. <br /><a href="https://www.sanjuancollege.edu/community/departments/child-and-family-development-center/">Child & Family Development Center</a></td><td>No information found.</td></tr>
        <tr><td>SANTA FE CC</td><td>No information found.</td><td>We offer year round care/education to children to age 5.<br /><a href="http://kidscampus.sfcc.edu/">Kids Campus Child Care</a></td><td>No information found.</td></tr>
        <tr><td>SIPI</td><td>The Housing & Recreation Department features two (2) traditional style residential facilities, which provides accommodations for approximately 288 students.<br /><a href="http://www.sipi.edu/students/studsvcs/rec/">Housing & Recreation Department</a></td><td>YDI/SIPI Early Childhood Learning Center is always accepting applications for children ages 6 weeks - 5 years old.<br /><a href="http://www.sipi.edu/childcare/">SIPI YDI Child Care Center</a></td><td>No information found.</td></tr>
        <tr><td>UNM-GALLUP</td><td>No housing available.</td><td>UNM-Gallup Early Childhood and Family Center (ECFC) serves young children of students, faculty, staff and community with care and learning using best practices and a Reggio Emilia inspired approach.<br /><a href="http://www.gallup.unm.edu/ecfc">Early Childhood and Family Center</a></td><td>No information found.</td></tr>
        <tr><td>UNM-LOS ALAMOS</td><td>It is the goal of UNM-LA to provide the safest, most affordable housing options possible for our students. In our ongoing effort to accommodate the housing needs of our students, we have partnered with the Los Alamos Chamber of Commerce to provide an up-to-date listing of off-campus housing resources.<br /><a href="http://losalamos.unm.edu/students/housing/">UNM-LA Student Housing</td><td>Childcare for children who are preschool age or younger will be provided at the Ark Child Development Center. Please call the Ark at 662-4822 to sign up.</td><td>At UNM Los Alamos, we understand that parents and families play an integral part of the college experience.<br /><a href="http://losalamos.unm.edu/community/parents-families/index.html">UNM-LA Parents & Families</a></td></tr>
        <tr><td>UNM-TAOS</td><td>No housing available.</td><td>The Kid's Campus serves children 6 weeks to 5 years of age.<br /><a href="http://taos.unm.edu/kids-campus/index.html">Kid's Campus</a></td><td><a href="http://taos.unm.edu/triomathsci/parents.html">Parents Resources</a></td></tr>
        <tr><td>UNM-VALENCIA</td><td>No housing available.</td><td>A library and Learning Resource Center were added in 1994, extensive renovations in Spring 1995 provided additional classroom and office space, and the completion of the Student/Community Center in the Spring 2000 added additional classrooms, office space, and a wellness/fitness center and child care facility.<br /><a href="http://valencia.unm.edu/academics/Catalog/archive/catalog-2014-2016.pdf">Catalog</a></td><td>No information found.</td></tr>
      </table>
    </div>
     <div class="clear"></div>
    <div class="container">
      <?php include 'includes/footer.php'; ?>
